org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.73
neo_version_range=[26.1.2,)

mod_id=pvp_flagging
mod_version=26.1.2-1.1.2
mod_group_id=io.redspace

mod_name=PVP Flagging
mod_license=All Rights Reserved
mod_authors=\n   Iron431 https://github.com/iron431\n   Smalls https://github.com/lab3
mod_description=Allows players to flag/unflag themselves for PVP and server operators to set up pvp zones
mod_credits=
mod_issue_tracker=https://github.com/Respace-io/pvp-flagging/issues
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/pvp-flagging
mod_logo_file=pvp-flagging.png
